### ISSUE TITLE
Make setup.py idiomatic

### ISSUE THREAD

**Issue by tommyod** [tommyod/treedoc#13]
## Reading

- Look at `setup.py` in [other projects](https://github.com/tommyod/treedoc/issues/5#issuecomment-488324435).
- Skim [this page](https://packaging.python.org/guides/distributing-packages-using-setuptools/).

## Our setup.py

- Make sure it follows best practices.
- Add relevant keywords which are currently not present.
- Comment and document keywords which are not intuitive.

Relatively simple task, orthogonal to other work. No rush to complete. @smu095 ?

**Comment by smu095** [comment]
I'll take it!

**Comment by smu095** [comment]
This issue has been adressed in PR #26.
