### ISSUE TITLE
Aesthetics of README

### ISSUE THREAD

**Issue by smu095** [tommyod/treedoc#14]
The current version of `README` is a great starting point. What follows is a short list of tasks related to aesthetics that are not strictly necessary, but which would in my opinion raise the overall presentation of the package:

- [x] Think of a concise and clever tagline (as @tommyod has already suggested)
- [x] Make a simple logo
- [x] Make some animated GIFs detailing usage and features

Concerning the last point, I have found a pretty good Mac-app which makes this really easy. Here's an example:

![treedoc1](https://user-images.githubusercontent.com/17871168/57430343-af349900-722f-11e9-8c1c-bfb1043a9d12.gif)

We should brainstorm about some examples which show some interesting features of `treedoc`, e.g. using it in conjunction with `grep`, etc.

Please comment if you have on any other suggestions related to visual presentation of the package, and I will add them to the list above.

**Comment by tommyod** [comment]
+1 on all points raised. Presentation is important and we must spent time on it. The animated gif is fantastic, and even the first-draft attached gif is beautiful and summarizes exactly what the package does.

**Comment by teenageknight** [comment]
I think that I might be able to help with some of these. I dont know about the tagline yet, but I can work with on the GIFS for the usage. I have windows not mac but I can make them look professional. Also, I know someone in graphics and design that can help with a logo. Just wondering if I would be of any help or have y'all already got someone for this.

**Comment by smu095** [comment]
Here are some initial proposals for the `treedoc`logo:

![treedoc_white_small](https://user-images.githubusercontent.com/17871168/57806336-32d61480-775f-11e9-943e-fa52b5dad034.png)
![treedoc_white_bold_small](https://user-images.githubusercontent.com/17871168/57806345-35386e80-775f-11e9-8e8e-43adf8be9d28.png)
![treedoc_green_small](https://user-images.githubusercontent.com/17871168/57806349-379ac880-775f-11e9-9f8b-482eebee6fbf.png)
![treedoc_green_bold_small](https://user-images.githubusercontent.com/17871168/57806351-38cbf580-775f-11e9-808d-fe6ea5d2b636.png)

I think I prefer prefer the light typeface over the bold, but I'm undecided on colour (my terminal is green).

**Comment by tommyod** [comment]
Good! I prefer light. It might look better with rounded corners, or with inverted colors (since the README is white).

I found a program called "peek" for Ubuntu for recording gifs too:

![treedoc2](https://user-images.githubusercontent.com/10076072/57827260-ff1edd00-77a6-11e9-8237-607cb182ea6b.gif)

**Comment by smu095** [comment]
Thanks for the feedback! Here are light typeface in both colours with rounded corners:

![treedoc_green_rounded_small](https://user-images.githubusercontent.com/17871168/57885941-66cb3b80-782c-11e9-96ed-e8f333c3606d.png)
![treedoc_white_rounded_small](https://user-images.githubusercontent.com/17871168/57885961-73e82a80-782c-11e9-9c22-c2fb9ffcd93b.png)

And here is the black-and-white version inverted (I added a stroke to the edges to make it pop):

![treedoc_white_rounded_inverted_small](https://user-images.githubusercontent.com/17871168/57886469-962e7800-782d-11e9-97ae-ce3cced6454c.png)

Rounded corners definitely looks better, good call. I think I prefer the black background though, stronger connotations to the terminal. Any thoughts @tommyod ?

I'll get on the gif-making ASAP.

**Comment by tommyod** [comment]
Black background looks good. Let's go for it! Should we decide to change it in the future that's possible too. Please upload all versions, since we might want to use different versions in different settings.
